name: Релиз проекта

on:
  workflow_dispatch:
    inputs:
      updateType:
        description: Тип релиза
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  changelog:
    uses: ExEr7um/workflows/.github/workflows/changelog.yml@v0.8.0
    with:
      updateType: ${{ inputs.updateType }}

  release:
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - name: Запуск деплоя
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          event-type: deploy
